/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/zalando-incubator/stackset-controller/pkg/apis/zalando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStackSets implements StackSetInterface
type FakeStackSets struct {
	Fake *FakeZalandoV1
	ns   string
}

var stacksetsResource = v1.SchemeGroupVersion.WithResource("stacksets")

var stacksetsKind = v1.SchemeGroupVersion.WithKind("StackSet")

// Get takes name of the stackSet, and returns the corresponding stackSet object, and an error if there is any.
func (c *FakeStackSets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.StackSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(stacksetsResource, c.ns, name), &v1.StackSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.StackSet), err
}

// List takes label and field selectors, and returns the list of StackSets that match those selectors.
func (c *FakeStackSets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StackSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(stacksetsResource, stacksetsKind, c.ns, opts), &v1.StackSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.StackSetList{ListMeta: obj.(*v1.StackSetList).ListMeta}
	for _, item := range obj.(*v1.StackSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stackSets.
func (c *FakeStackSets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(stacksetsResource, c.ns, opts))

}

// Create takes the representation of a stackSet and creates it.  Returns the server's representation of the stackSet, and an error, if there is any.
func (c *FakeStackSets) Create(ctx context.Context, stackSet *v1.StackSet, opts metav1.CreateOptions) (result *v1.StackSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(stacksetsResource, c.ns, stackSet), &v1.StackSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.StackSet), err
}

// Update takes the representation of a stackSet and updates it. Returns the server's representation of the stackSet, and an error, if there is any.
func (c *FakeStackSets) Update(ctx context.Context, stackSet *v1.StackSet, opts metav1.UpdateOptions) (result *v1.StackSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(stacksetsResource, c.ns, stackSet), &v1.StackSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.StackSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStackSets) UpdateStatus(ctx context.Context, stackSet *v1.StackSet, opts metav1.UpdateOptions) (*v1.StackSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(stacksetsResource, "status", c.ns, stackSet), &v1.StackSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.StackSet), err
}

// Delete takes name of the stackSet and deletes it. Returns an error if one occurs.
func (c *FakeStackSets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(stacksetsResource, c.ns, name, opts), &v1.StackSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStackSets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(stacksetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.StackSetList{})
	return err
}

// Patch applies the patch and returns the patched stackSet.
func (c *FakeStackSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StackSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stacksetsResource, c.ns, name, pt, data, subresources...), &v1.StackSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.StackSet), err
}
