version: "2"

run:
  concurrency: 4

linters:
  disable-all: true
  enable:
  - errcheck
  - govet
  - ineffassign
  - staticcheck
  - unused
  exclusions:
    rules:
    - linters:
      - staticcheck
      text: "QF1008"
