version: "2017-09-20"
pipeline:
- id: build
  overlay: ci/golang
  type: script
  cache:
    paths:
    - /go/pkg/mod       # pkg cache for Go modules
    - ~/.cache/go-build # Go build cache
  commands:
  - desc: test
    cmd: |
      make check
      make test
  - desc: build
    cmd: |
      make build.docker
  - desc: push
    cmd: |
      IMAGE=registry-write.opensource.zalan.do/teapot/stackset-controller-test
      IMAGE=$IMAGE VERSION=$CDP_BUILD_VERSION make build.push

- id: e2e
  type: process
  desc: "E2E Tests"
  target: stups-test
  process: microservice_standard_test
  config:
    apply_manifests:
      env:
      - name: APPLICATION
        value: stackset-controller-test
      - name: DEPLOYMENT_PATH
        value: e2e
      - name: IMAGE
        value: "registry.opensource.zalan.do/teapot/stackset-controller-test:#{CDP_BUILD_VERSION}"
      - name: CONTROLLER_ID
        value: "#{CDP_BUILD_VERSION}"
      - name: CLUSTER_DOMAIN
        value: stups-test.zalan.do
    end2end_tests:
      metadata:
        name: e2e
      spec:
        serviceAccountName: stackset-controller
        restartPolicy: Never
        containers:
          - name: e2e
            image: "registry.opensource.zalan.do/teapot/stackset-controller-test-e2e:#{CDP_BUILD_VERSION}"
            command: ["/e2e"]
            env:
              - name: "CONTROLLER_ID"
                value: "#{CDP_BUILD_VERSION}"
              - name: CLUSTER_DOMAIN
                value: stups-test.zalan.do
              - name: "E2E_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace

- id: buildprod
  when:
    branch: master
  overlay: ci/golang
  type: script
  env:
    GOFLAGS: "-mod=readonly"
  cache:
    paths:
    - /go/pkg/mod       # pkg cache for Go modules
    - ~/.cache/go-build # Go build cache
  commands:
  - desc: push
    cmd: |
      VERSION=$(git describe --tags --always)
      IMAGE=registry-write.opensource.zalan.do/teapot/stackset-controller
      IMAGE=$IMAGE VERSION=$VERSION make build.docker
      git diff --stat --exit-code
      IMAGE=$IMAGE VERSION=$VERSION make build.push
