apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: e2e-deploy-sample
  labels:
    application: "e2e-deploy-sample"
  annotations:
    "stackset-controller.zalando.org/controller": "{{{CONTROLLER_ID}}}"
spec:
  ingress:
    hosts:
    - "e2e-deploy-sample.{{{CLUSTER_DOMAIN}}}"
    backendPort: 80
  stackLifecycle:
    scaledownTTLSeconds: 300
    limit: 3
  stackTemplate:
    spec:
      version: "{{{CDP_BUILD_VERSION}}}"
      replicas: 2
      configurationResources:
      - configMapRef:
          name: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-reference-config
      - secretRef:
          name: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-reference-secret
      - platformCredentialsSet:
          name: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-pcs
          tokens:
            sample-token:
              privileges:
              - com.zalando::foobar.read
      autoscaler:
        minReplicas: 2
        maxReplicas: 2
        metrics:
        - type: CPU
          averageUtilization: 50
        - type: Ingress
          average: 20000m
      podTemplate:
        metadata:
          labels:
            application: "e2e-deploy-sample"
        spec:
          containers:
          - name: skipper
            image: ghcr.io/zalando/skipper:v0.15.33
            args:
            - skipper
            - -inline-routes
            - '* -> inlineContent("OK") -> <shunt>'
            - -address=:80
            ports:
            - containerPort: 80
            resources:
              requests:
                cpu: 1m
                memory: 100Mi
              limits:
                cpu: 1m
                memory: 100Mi
            volumeMounts:
            - name: my-reference-config
              mountPath: /etc/my-reference-config
              readOnly: true
            - name: my-reference-secret
              mountPath: /etc/my-reference-secret
              readOnly: true
          volumes:
          - name: my-reference-config
            configMap:
              name: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-reference-config
          - name: my-reference-secret
            secret:
              secretName: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-reference-secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-reference-config
  labels:
    application: "e2e-deploy-sample"
data:
  something_is: configured_by_reference

---

apiVersion: v1
kind: Secret
metadata:
  name: e2e-deploy-sample-{{{CDP_BUILD_VERSION}}}-my-reference-secret
  labels:
    application: "e2e-deploy-sample"
data:
  something_is: c2VjcmV0bHlfY29uZmlndXJlZF9ieV9yZWZlcmVuY2U=
