apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: e2e-deploy-sample
  labels:
    application: "e2e-deploy-sample"
  annotations:
    "stackset-controller.zalando.org/controller": "{{{CONTROLLER_ID}}}"
spec:
  ingress:
    hosts:
    - "e2e-deploy-sample.{{{CLUSTER_DOMAIN}}}"
    backendPort: 80
  stackLifecycle:
    scaledownTTLSeconds: 300
    limit: 3
  stackTemplate:
    spec:
      version: "{{{CDP_BUILD_VERSION}}}"
      replicas: 2
      autoscaler:
        minReplicas: 2
        maxReplicas: 2
        metrics:
        - type: CPU
          averageUtilization: 50
      podTemplate:
        metadata:
          labels:
            application: "e2e-deploy-sample"
        spec:
          containers:
          - name: "e2e-deploy-sample"
            image: nginx
            ports:
            - containerPort: 80
            resources:
              requests:
                cpu: 1m
                memory: 100Mi
              limits:
                cpu: 1m
                memory: 100Mi
