/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/zalando-incubator/stackset-controller/pkg/apis/zalando.org/v1"
	scheme "github.com/zalando-incubator/stackset-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// StackSetsGetter has a method to return a StackSetInterface.
// A group's client should implement this interface.
type StackSetsGetter interface {
	StackSets(namespace string) StackSetInterface
}

// StackSetInterface has methods to work with StackSet resources.
type StackSetInterface interface {
	Create(ctx context.Context, stackSet *v1.StackSet, opts metav1.CreateOptions) (*v1.StackSet, error)
	Update(ctx context.Context, stackSet *v1.StackSet, opts metav1.UpdateOptions) (*v1.StackSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, stackSet *v1.StackSet, opts metav1.UpdateOptions) (*v1.StackSet, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.StackSet, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.StackSetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StackSet, err error)
	StackSetExpansion
}

// stackSets implements StackSetInterface
type stackSets struct {
	*gentype.ClientWithList[*v1.StackSet, *v1.StackSetList]
}

// newStackSets returns a StackSets
func newStackSets(c *ZalandoV1Client, namespace string) *stackSets {
	return &stackSets{
		gentype.NewClientWithList[*v1.StackSet, *v1.StackSetList](
			"stacksets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.StackSet { return &v1.StackSet{} },
			func() *v1.StackSetList { return &v1.StackSetList{} }),
	}
}
