/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/zalando-incubator/stackset-controller/pkg/apis/zalando/v1"
	scheme "github.com/zalando-incubator/stackset-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StackSetsGetter has a method to return a StackSetInterface.
// A group's client should implement this interface.
type StackSetsGetter interface {
	StackSets(namespace string) StackSetInterface
}

// StackSetInterface has methods to work with StackSet resources.
type StackSetInterface interface {
	Create(*v1.StackSet) (*v1.StackSet, error)
	Update(*v1.StackSet) (*v1.StackSet, error)
	UpdateStatus(*v1.StackSet) (*v1.StackSet, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.StackSet, error)
	List(opts metav1.ListOptions) (*v1.StackSetList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.StackSet, err error)
	StackSetExpansion
}

// stackSets implements StackSetInterface
type stackSets struct {
	client rest.Interface
	ns     string
}

// newStackSets returns a StackSets
func newStackSets(c *ZalandoV1Client, namespace string) *stackSets {
	return &stackSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the stackSet, and returns the corresponding stackSet object, and an error if there is any.
func (c *stackSets) Get(name string, options metav1.GetOptions) (result *v1.StackSet, err error) {
	result = &v1.StackSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stacksets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StackSets that match those selectors.
func (c *stackSets) List(opts metav1.ListOptions) (result *v1.StackSetList, err error) {
	result = &v1.StackSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stacksets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested stackSets.
func (c *stackSets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("stacksets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a stackSet and creates it.  Returns the server's representation of the stackSet, and an error, if there is any.
func (c *stackSets) Create(stackSet *v1.StackSet) (result *v1.StackSet, err error) {
	result = &v1.StackSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("stacksets").
		Body(stackSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a stackSet and updates it. Returns the server's representation of the stackSet, and an error, if there is any.
func (c *stackSets) Update(stackSet *v1.StackSet) (result *v1.StackSet, err error) {
	result = &v1.StackSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stacksets").
		Name(stackSet.Name).
		Body(stackSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *stackSets) UpdateStatus(stackSet *v1.StackSet) (result *v1.StackSet, err error) {
	result = &v1.StackSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stacksets").
		Name(stackSet.Name).
		SubResource("status").
		Body(stackSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the stackSet and deletes it. Returns an error if one occurs.
func (c *stackSets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stacksets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *stackSets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stacksets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched stackSet.
func (c *stackSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.StackSet, err error) {
	result = &v1.StackSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("stacksets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
