apiVersion: zalando.org/v1
kind: StackSet
metadata:
  name: my-app
spec:
  ingress:
    hosts:
      - my-app.example.org
      - alt.name.org
    backendPort: 80
  traffic:
  - stackName: my-app-v1
    weight: 40
  - stackName: my-app-v2
    weight: 60
  minReadyPercent: 90
  stackLifecycle:
    scaledownTTLSeconds: 300
    limit: 5
  stackTemplate:
    spec:
      version: v1
      replicas: 3
      horizontalPodAutoscaler:
        minReplicas: 3
        maxReplicas: 10
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 50
      podTemplate:
        spec:
          containers:
          - name: skipper
            image: registry.opensource.zalan.do/teapot/skipper:latest
            args:
            - skipper
            - -inline-routes
            - '* -> inlineContent("OK") -> <shunt>'
            - -address=:80
            ports:
            - containerPort: 80
              name: ingress
            resources:
              limits:
                cpu: 10m
                memory: 50Mi
              requests:
                cpu: 10m
                memory: 50Mi
